# Schema for the configuration files of the Optit module.

optit.settings:
  type: config_object
  label: 'Optit settings'
  mapping:
    username:
      type: string
      label: 'API username'
    password:
      type: string
      label: 'API password'