<?php


/**
 * Implementation of hook_help().
 */
function optit_send_help($path, $arg) {
  switch ($path) {
    case "admin/structure/optit/send/sms":
      return "<p>" . t("Send a text message to the subscribed members of a keyword.") . "</p>";
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function optit_send_menu() {

  $items['admin/structure/optit/send'] = array(
    'title' => 'Send message',
    'description' => 'Send messages to your subscribers.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/structure/optit/send/sms'] = array(
    'title' => 'SMS',
    'description' => 'Choose a keyword and send an SMS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_keyword'),
    'access arguments' => array('optit send message'),
  );

  $items['admin/structure/optit/send/mms'] = array(
    'title' => 'MMS',
    'description' => 'Choose a keyword and send an MMS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_keyword_mms'),
    'access arguments' => array('optit send message'),
  );

  $items['admin/structure/optit/keywords/%/subscriptions/sms'] = array(
    'title' => 'Send SMS',
    'description' => 'Send SMS to all keyword subscribers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_keyword', 4),
    'access arguments' => array('optit send message'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/structure/optit/keywords/%/subscriptions/mms'] = array(
    'title' => 'Send MMS',
    'description' => 'Send MMS to all keyword subscribers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_keyword_mms', 4),
    'access arguments' => array('optit send message'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/structure/optit/keywords/%/subscriptions/message/%'] = array(
    'title' => 'Send message',
    'description' => 'Send message to keyword subscribers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_keyword', 4, 6),
    'access arguments' => array('optit send message'),
  );

  $items['admin/structure/optit/keywords/%/interests/%/subscriptions/message'] = array(
    'title' => 'Send message',
    'description' => 'Send message to interest subscribers.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_send_interest', 4, 6),
    'access arguments' => array('optit send message'),
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;

}


function optit_send_keyword($form, $form_state, $keyword_id = NULL, $phone = NULL) {
  $optit = optit_instantiate();
  $keywords = $optit->keywordsGet();
  $options = array();
  foreach ($keywords as $keyword) {
    $options[$keyword->get('id')] = $keyword->get('keyword_name');
  }


  if (!$keyword_id) {
    $form['keyword_id'] = array(
      '#title' => t('Keyword'),
      '#description' => t('Please choose a keyword.'),
      '#type' => 'select',
      '#options' => $options,
      '#required' => TRUE,
    );
  }
  else {
    $form['keyword_id'] = array(
      '#type' => 'value',
      '#value' => $keyword_id,
      // Okay, following line is really ugly, but I need it for cleaner validation, otherwise, I'd have to run two optit queries.
      '#options' => $options,
    );
  }

  $form['phone'] = array(
    '#type' => 'value',
    '#value' => $phone,
  );

  $form['title'] = array(
    '#title' => t('Title'),
    '#description' => t('Please enter a title of message. This does not appear in the text message and is just used in the application as a short description of your message.'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  $form['message'] = array(
    '#title' => t('Message'),
    '#description' => t('Please enter a text message. The message must be less than 160 characters including your keyword in the beginning of the message.'),
    '#type' => 'textarea',
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#weight' => 10,
  );
  return $form;
}

function optit_send_keyword_mms($form, $form_state, $keyword_id = NULL, $phone = NULL) {
  $form['media'] = array(
    '#type' => 'file',
    '#title' => t('Media file'),
    '#name' => 'files[media]',
    '#description' => t('Upload a media file to be sent with MMS. Allowed extensions: jpg, jpeg, png, gif, vnd, wap, wbpm, bpm, amr, x-wav, aac, qcp, 3gpp, 3gpp2'),
    '#weight' => 9
  );

  $form += optit_send_keyword($form, $form_state, $keyword_id, $phone);

  return $form;
}

function optit_send_keyword_validate($form, &$form_state) {
  // Make sure keyword and message are less than 160 characters.
  $keyword_id = $form_state['values']['keyword_id'];
  $message = $form_state['values']['message'];
  $keyword = $form['keyword_id']['#options'][$keyword_id];

//  // If phone number was provided, it needs to be made of 11 digits.
//  $phone = $form_state['values']['phone'];
//  if (isset($phone)) {
//    if (!optit_phone_validate($phone)) {
//      form_set_error('phone', t('Invalid phone number. Mobile phone number should include country code and be 11 digit long. Example: 12225551212'));
//    }
// }

  $length = strlen($keyword . ': ' . $message);
  if ($length > 160) {
    form_set_error('message', t('The message must be less than 160 characters including your keyword in the beginning of the message. Your message has :length characters', array(':length' => $length)));
  };
}

function optit_send_keyword_submit($form, &$form_state) {
  $keyword_id = $form_state['values']['keyword_id'];
  $message = $form_state['values']['message'];
  $title = $form_state['values']['title'];

  $optit = optit_instantiate();
  if ($form_state['values']['phone']) {
    $success = $optit->messagePhone($form_state['values']['phone'], $keyword_id, $title, $message);
  }
  else {
    $success = $optit->messageKeyword($keyword_id, $title, $message);
  }

  if ($success) {
    drupal_set_message(t('Message was successfully sent.'));
  }
  else {
    drupal_set_message(t('The message could not be sent. Please consult error log for details.', 'error'));
  }
}


function optit_send_keyword_mms_validate($form, &$form_state) {

  $validators = array(
    'file_validate_extensions' => array('jpg jpeg png gif vnd wap wbpm bpm amr x-wav aac qcp 3gpp 3gpp2'),
  );

  // Save temporary file.
  $file = file_save_upload('media', $validators);

  // If file was saved, move it to public folder.
  if ($file) {
    // Make sure public folder exists and is writable.
    $dir = 'public://optit';
    if (!file_prepare_directory($dir, FILE_CREATE_DIRECTORY)) {
      drupal_mkdir($dir);
    }
    if ($file = file_move($file, "{$dir}/{$file->filename}")) {
      $form_state['values']['media'] = $file;
    }
    else {
      form_set_error('media', t('Failed to write the uploaded file the file folder.'));
    }
  }
}

function optit_send_keyword_mms_submit($form, &$form_state) {
  $keyword_id = $form_state['values']['keyword_id'];
  $title = $form_state['values']['title'];
  $message = $form_state['values']['message'];
  $content_url = NULL;
  if($form_state['values']['media']) {
    $content_url = file_create_url($form_state['values']['media']->uri);
  }

  $optit = optit_instantiate();
  $success = $optit->messageKeywordMMS($keyword_id, $title, $message, $content_url);

  if ($success) {
    drupal_set_message(t('Message was successfully sent.'));
  }
  else {
    drupal_set_message(t('The message could not be sent. Please consult error log for details.'), 'error');
  }
}


function optit_send_interest($form, $form_state, $keyword_id, $interest_id) {

  $form['interest_id'] = array(
    '#type' => 'value',
    '#value' => $interest_id,
  );

  $form['keyword_id'] = array(
    '#type' => 'value',
    '#value' => $keyword_id,
  );

  $form['title'] = array(
    '#title' => t('Title'),
    '#description' => t('Please enter a title of message. This does not appear in the text message and is just used in the application as a short description of your message.'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );

  $form['message'] = array(
    '#title' => t('Message'),
    '#description' => t('Please enter a text message. The message must be less than 160 characters including your keyword in the beginning of the message.'),
    '#type' => 'textarea',
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function optit_send_interest_validate($form, &$form_state) {
  // Make sure keyword and message are less than 160 characters.
  $interest_id = $form_state['values']['interest_id'];
  $message = $form_state['values']['message'];

  $optit = optit_instantiate();
  $interest = $optit->interestGet($interest_id);

  $length = strlen($interest->get('name') . ': ' . $message);

  if ($length > 160) {
    form_set_error('message', t('The message must be less than 160 characters including your keyword in the beginning of the message. Your message has :length characters', array(':length' => $length)));
  };
}

function optit_send_interest_submit($form, &$form_state) {
  $interest_id = $form_state['values']['interest_id'];
  $message = $form_state['values']['message'];
  $title = $form_state['values']['title'];

  $optit = optit_instantiate();
  $success = $optit->messageInterest($interest_id, $title, $message);

  if ($success) {
    drupal_set_message(t('Message was successfully sent.'));
  }
  else {
    drupal_set_message(t('The message could not be sent. Please consult error log for details.'), 'error');
  }

  if (!isset($_GET['destination'])) {
    // default redirection could be better...
    $form_state['redirect'] = "admin/structure/optit/keywords/{$form_state['values']['keyword_id']}/interests/{$form_state['values']['interest_id']}/subscriptions";
  }
}
