<?php

/**
 * Implements hook_menu().
 */
function optit_bulk_menu() {

  $items['admin/structure/optit/send/bulk'] = array(
    'title' => 'Bulk',
    'description' => 'Send bulk messages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_bulk_list'),
    'access arguments' => array('optit send message'),
  );

  return $items;
}

/**
 * Form API implementation for list of all messages in bulk, sending and/or deletion of messages in bulk.
 *
 * @route("admin/structure/optit/send/bulk")
 */
function optit_bulk_list($form, $form_state) {
  $optit = optit_instantiate();

  // If there is nothing in bulk, return appropriate message.
  if (!isset($_SESSION['optit_bulk']) || count($_SESSION['optit_bulk']) == 0) {
    $form['markup'] = array(
      '#markup' => t('The bulk messaging list is empty. Please use appropriate message forms to create messages and add them to bulk.')
    );
    return $form;
  }

  // Start building vars for theme_table.
  $vars = array(
    'header' => array(
      t('Title'),
      t('Message'),
      t('Recipients'),
    ),
    'rows' => array()
  );

  // Iterate through keywords in bulk.
  foreach ($_SESSION['optit_bulk'] as $keyword_id => $messages) {
    $keyword = $optit->keywordGet($keyword_id);
    $keywordName = $keyword->get('keyword_name');
    // Iterate through messages in a keyword.
    foreach ($messages as $message) {
      $messageTitle = $message['title'];
      $messageMessage = $message['message'];
      $vars['rows'][] = array(
        $messageTitle,
        "<b>{$keywordName}:</b> {$messageMessage}",
        theme('item_list', array('items' => $message['phones']))
      );
    }
  }

  $form['markup'] = array(
    '#markup' => theme('table', $vars)
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send messages'),
    '#submit' => array('optit_bulk_messages_submit'),
  );

  $form['clear'] = array(
    '#type' => 'submit',
    '#value' => t('Clear the list'),
    '#submit' => array('optit_bulk_messages_clear'),
  );

  return $form;
}

/**
 * Form submission callback: Send messages.
 */
function optit_bulk_messages_submit($form, &$form_state) {
  $optit = optit_instantiate();
  $success = $optit->messageBulkArray($_SESSION['optit_bulk']);

  if ($success) {
    drupal_set_message(t('Bulk messages were sent successfully.'));
    optit_bulk_messages_clear($form, $form_state);
  }
  else {
    drupal_set_message(t('There was an error processing bulk messaging. Please check error logs for more information.'), 'error');
  }
}

/**
 * Form submission callback: Clear the bulk.
 */
function optit_bulk_messages_clear($form, &$form_state) {
  $_SESSION['optit_bulk'] = array();
}

/**
 * Implements hook_form_alter().
 */
function optit_bulk_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'optit_send_keyword') {
    $form['add_to_bulk'] = array(
      '#type' => 'submit',
      '#value' => t('Add to bulk'),
      '#submit' => array('optit_bulk_add_message_to_bulk'),
    );
  }
}

/**
 * Form submission callback: Add message to bulk.
 */
function optit_bulk_add_message_to_bulk($form, &$form_state) {
  $optit = optit_instantiate();

  $phones = array();
  // If phone number was not set -- message all subscribers to the keyword.
  if (!$form_state['values']['phone']) {
    $subscriptions = $optit->subscriptionsGet($form_state['values']['keyword_id']);
    foreach ($subscriptions as $subscription) {
      $phones[] = $subscription->get('phone');
    }
  }
  // Else iterate through submitted values and make a nice flat array
  else {
    // @todo: Wasn't this supposed to be validation's responsibility?!?!
    foreach ($form_state['values']['phone'] as $phone => $selected) {
      if ($selected) {
        $phones[] = $phone;
      }
    }
  }

  $message = array(
    'title' => $form_state['values']['title'],
    'message' => $form_state['values']['message'],
    'phones' => $phones
  );

  _optit_bulk_add_message_to_session($message, $form_state['values']['keyword_id']);
}

/**
 * Helper function which adds message to session variable.
 */
function _optit_bulk_add_message_to_session($message, $id) {
  if (!isset($_SESSION['optit_bulk'])) {
    $_SESSION['optit_bulk'] = array();
  }

  if (!isset($_SESSION['optit_bulk'][$id])) {
    $_SESSION['optit_bulk'][$id] = array();
  }

  $_SESSION['optit_bulk'][$id][] = $message;

  drupal_set_message(t('Message successfully added to the bulk.'));
}
