<?php

/**
 * Implements hook_menu().
 */
function optit_bulk_menu() {

  $items['admin/structure/optit/bulk'] = array(
    'title' => 'Bulk messaging',
    'description' => 'Send bulk SMS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_bulk_list'),
    'access arguments' => array('optit send message'),
  );

  $items['admin/structure/optit/bulk/sms'] = array(
    'title' => 'Bulk SMS',
    'type' => MENU_DEFAULT_LOCAL_TASK
  );

  $items['admin/structure/optit/bulk/mms'] = array(
    'title' => 'Bulk MMS',
    'description' => 'Send bulk MMS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('optit_bulk_mms_list'),
    'access arguments' => array('optit send message'),
    'type' => MENU_LOCAL_TASK
  );

  return $items;
}

/**
 * Form API implementation for list of all messages in bulk, sending and/or deletion of messages in bulk.
 *
 * @route("admin/structure/optit/send/bulk")
 */
function optit_bulk_list($form, $form_state) {
  if ($markup = _optit_bulk_prepare_markup('optit_bulk')) {
    $form['markup'] = array(
      '#markup' => $markup
    );
  }
  // If there is nothing in bulk, return appropriate message.
  else {
    $form['markup'] = array(
      '#markup' => t('The bulk messaging list is empty. Please use appropriate message forms to create messages and add them to bulk.')
    );
    return $form;
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send messages'),
    '#submit' => array('optit_bulk_messages_submit'),
  );

  $form['clear'] = array(
    '#type' => 'submit',
    '#value' => t('Clear the list'),
    '#submit' => array('optit_bulk_messages_clear'),
  );

  return $form;
}

function optit_bulk_mms_list($form, &$form_state) {
  if ($markup = _optit_bulk_prepare_markup('optit_bulk_mms')) {
    $form['markup'] = array(
      '#markup' => $markup
    );
  }
  // If there is nothing in bulk, return appropriate message.
  else {
    $form['markup'] = array(
      '#markup' => t('The bulk mms list is empty. Please use appropriate mms submission forms to create messages and add them to bulk.')
    );
    return $form;
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send messages'),
    '#submit' => array('optit_bulk_mms_submit'),
  );

  $form['clear'] = array(
    '#type' => 'submit',
    '#value' => t('Clear the list'),
    '#submit' => array('optit_bulk_mms_clear'),
  );

  return $form;
}

/**
 * Form submission callback: Send messages.
 */
function optit_bulk_messages_submit($form, &$form_state) {
  $optit = optit_instantiate();
  $success = $optit->messageBulkArray($_SESSION['optit_bulk']);

  if ($success) {
    drupal_set_message(t('Bulk messages were sent successfully.'));
    optit_bulk_messages_clear($form, $form_state);
  }
  else {
    drupal_set_message(t('There was an error processing bulk messaging. Please check error logs for more information.'), 'error');
  }
}


function optit_bulk_mms_submit($form, &$form_state) {
  $optit = optit_instantiate();
  $success = $optit->messageBulkMMSArray($_SESSION['optit_bulk_mms']);

  if ($success) {
    drupal_set_message(t('Bulk messages were sent successfully.'));
    optit_bulk_messages_clear($form, $form_state);
  }
  else {
    drupal_set_message(t('There was an error processing bulk messaging. Please check error logs for more information.'), 'error');
  }
}

/**
 * Form submission callback: Clear the bulk.
 */
function optit_bulk_mms_clear($form, &$form_state) {
  $_SESSION['optit_bulk_mms'] = array();
}

/**
 * Form submission callback: Clear the bulk.
 */
function optit_bulk_messages_clear($form, &$form_state) {
  $_SESSION['optit_bulk'] = array();
}

/**
 * Implements hook_form_alter().
 */
function optit_bulk_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'optit_send_keyword':
      $form['add_to_bulk'] = array(
        '#type' => 'submit',
        '#weight' => 50,
        '#value' => t('Add to bulk'),
        '#submit' => array('optit_bulk_add_message_to_bulk'),
      );
      break;
    case 'optit_send_keyword_mms':
      $form['add_to_bulk'] = array(
        '#type' => 'submit',
        '#weight' => 50,
        '#value' => t('Add to bulk'),
        '#submit' => array('optit_bulk_add_mms_to_bulk'),
      );
      break;
  }
}

/**
 * Form submission callback: Add message to bulk.
 */
function optit_bulk_add_message_to_bulk($form, &$form_state) {
  $optit = optit_instantiate();

  $phones = array();
  // If phone number was not set -- message all subscribers to the keyword.
  if (!$form_state['values']['phone']) {
    $subscriptions = $optit->subscriptionsGet($form_state['values']['keyword_id']);
    foreach ($subscriptions as $subscription) {
      $phones[] = $subscription->get('phone');
    }
  }
  // Else iterate through submitted values and make a nice flat array
  else {
    // @todo: Wasn't this supposed to be validation's responsibility?!?!
    foreach ($form_state['values']['phone'] as $phone => $selected) {
      if ($selected) {
        $phones[] = $phone;
      }
    }
  }

  $message = array(
    'title' => $form_state['values']['title'],
    'message' => $form_state['values']['message'],
    'phones' => $phones
  );

  _optit_bulk_add_message_to_session($message, $form_state['values']['keyword_id']);
}


function optit_bulk_add_mms_to_bulk($form, &$form_state) {
  $optit = optit_instantiate();

  $phones = array();
  // If phone number was not set -- message all subscribers to the keyword.
  if (!$form_state['values']['phone']) {
    $subscriptions = $optit->subscriptionsGet($form_state['values']['keyword_id']);
    foreach ($subscriptions as $subscription) {
      $phones[] = $subscription->get('phone');
    }
  }
  // Else iterate through submitted values and make a nice flat array.
  else {
    // @todo: Wasn't this supposed to be validation's responsibility?!?!
    foreach ($form_state['values']['phone'] as $phone => $selected) {
      if ($selected) {
        $phones[] = $phone;
      }
    }
  }

  $message = array(
    'title' => $form_state['values']['title'],
    'message' => $form_state['values']['message'],
    'phones' => $phones,
    'content_url' => NULL
  );

  if ($form_state['values']['media']) {
    $message['content_url'] = file_create_url($form_state['values']['media']->uri);
  }

  _optit_bulk_add_message_to_session($message, $form_state['values']['keyword_id'], 'optit_bulk_mms');
}


/**
 * Helper function which adds message to session variable.
 */
function _optit_bulk_add_message_to_session($message, $id, $sessionVarName = 'optit_bulk') {
  if (!isset($_SESSION[$sessionVarName])) {
    $_SESSION[$sessionVarName] = array();
  }

  if (!isset($_SESSION[''][$id])) {
    $_SESSION[$sessionVarName][$id] = array();
  }

  $_SESSION[$sessionVarName][$id][] = $message;

  drupal_set_message(t('Message successfully added to the bulk.'));
}


function _optit_bulk_prepare_markup($sessionVarName) {
  $optit = optit_instantiate();

  if (!isset($_SESSION[$sessionVarName]) || count($_SESSION[$sessionVarName]) == 0) {
    return FALSE;
  }

  // Start building vars for theme_table.
  $vars = array(
    'header' => array(
      t('Title'),
      t('Message'),
      t('Recipients'),
    ),
    'rows' => array()
  );
  // Iterate through keywords in bulk.
  foreach ($_SESSION[$sessionVarName] as $keyword_id => $messages) {
    $keyword = $optit->keywordGet($keyword_id);
    $keywordName = $keyword->get('keyword_name');
    // Iterate through messages in a keyword.
    foreach ($messages as $message) {
      $messageTitle = $message['title'];
      $messageMessage = $message['message'];
      $phones = theme('item_list', array('items' => $message['phones']));
      $vars['rows'][] = array(
        $messageTitle,
        "<b>{$keywordName}:</b> {$messageMessage}",
        $phones
      );
    }
  }
  return theme('table', $vars);
}
